Fix GitHub Actions workflows

diff --git a/.github/workflows/quick-build.yml b/.github/workflows/quick-build.yml
--- a/.github/workflows/quick-build.yml
+++ b/.github/workflows/quick-build.yml
@@ -41,12 +41,15 @@ jobs:
         args: --server=sqlite --database=target/chinook-database-2.2.1.sqlite --title "Chinook Database, v2.2.1" --info-level=standard --command=schema --output-file chinook_schema_diagram.png --log-level=CONFIG
 
     - id: check-success
-      name: Check if the SchemaCrawler run succeeded
+      name: Fail the entire job if SchemaCrawler run failed
+      shell: bash
       run: |
-        [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] && echo "SchemaCrawler run succeeded" || exit ${{ steps.schemacrawler.outputs.exit_status }}
+        [ ${{ env.SC_EXIT_STATUS }} -eq 0 ] && echo "SchemaCrawler run succeeded" || echo "SchemaCrawler run failed"
+        [ ${{ env.SC_EXIT_STATUS }} -eq 0 ] || exit 1
 
     - id: checkin
       name: Checkin schema diagram created from the SchemaCrawler Action
+      shell: bash
       run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
