Do not check in diagram

diff --git a/.github/workflows/quick-build.yml b/.github/workflows/quick-build.yml
--- a/.github/workflows/quick-build.yml
+++ b/.github/workflows/quick-build.yml
@@ -79,6 +79,13 @@ jobs:
         entrypoint: /schemacrawler.sh
         args: --server=sqlite --database=chinook-database-2.2.1.sqlite --title "Chinook Database, v2.2.1" --info-level=standard --command=schema --output-file chinook_schema_diagram.png --log-level=CONFIG
 
+    - id: check-success
+      name: Fail the entire job if SchemaCrawler run failed
+      shell: bash
+      run: |
+        [ ${{ env.SC_EXIT_STATUS }} -eq 0 ] && echo "SchemaCrawler run succeeded" || echo "SchemaCrawler run failed"
+        [ ${{ env.SC_EXIT_STATUS }} -eq 0 ] || exit 1
+
 # UPLOAD SQLite DATABASE
     - id: upload-diagram
       name: Upload Artifacts
@@ -87,20 +94,3 @@ jobs:
         name: schema-diagram
         path: chinook_schema_diagram.png
         retention-days: 3
-
-    - id: check-success
-      name: Fail the entire job if SchemaCrawler run failed
-      shell: bash
-      run: |
-        [ ${{ env.SC_EXIT_STATUS }} -eq 0 ] && echo "SchemaCrawler run succeeded" || echo "SchemaCrawler run failed"
-        [ ${{ env.SC_EXIT_STATUS }} -eq 0 ] || exit 1
-
-    - id: push-generated-graph
-      uses: stefanzweifel/git-auto-commit-action@v5
-      with:
-        commit_message: "Update database schema diagram from CI build"
-        branch: main
-        commit_options: '--no-verify --no-signoff'
-        commit_user_name: "Sualeh Fatehi"
-        commit_user_email: "sualeh@hotmail.com"
-        commit_author: "Sualeh Fatehi <sualeh@hotmail.com>"
